import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().min(1),
    AUTH_SECRET: z.string().min(32),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    OPENAI_API_KEY: z.string().min(1).optional(),
    OPENAI_VISION_MODEL: z.string().min(1).optional(),
    STRIPE_SECRET_KEY: z.string().min(1).optional(),
    STRIPE_WEBHOOK_SECRET: z.string().min(1).optional(),
    STRIPE_PRO_PRICE_PLN: z.string().min(1).optional(),
    STRIPE_PRO_PRICE_EUR: z.string().min(1).optional(),
    STRIPE_PRO_PRICE_GBP: z.string().min(1).optional(),
    STRIPE_PRO_PRICE_USD: z.string().min(1).optional(),
    STRIPE_PREMIUM_PRICE_PLN: z.string().min(1).optional(),
    STRIPE_PREMIUM_PRICE_EUR: z.string().min(1).optional(),
    STRIPE_PREMIUM_PRICE_GBP: z.string().min(1).optional(),
    STRIPE_PREMIUM_PRICE_USD: z.string().min(1).optional(),
    BREVO_API_KEY: z.string().min(1).optional(),
    BREVO_FROM_EMAIL: z.string().min(1).optional(),
    CONTACT_INBOX_EMAIL: z.string().email().optional(),
    SENTRY_AUTH_TOKEN: z.string().min(1).optional(),
    UPSTASH_REDIS_REST_URL: z.string().url().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1).optional(),
    CRON_SECRET: z.string().min(1).optional(),
    POSTHOG_API_KEY: z.string().min(1).optional(),
    ENABLE_AI: z.enum(['true', 'false']).optional(),
    SUPABASE_URL: z.string().url().optional(),
    SUPABASE_SERVICE_ROLE_KEY: z.string().min(1).optional(),
  },
  client: {
    NEXT_PUBLIC_APP_URL: z.string().url(),
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: z.string().min(1).optional(),
    NEXT_PUBLIC_POSTHOG_KEY: z.string().min(1).optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().url().optional(),
    NEXT_PUBLIC_SENTRY_DSN: z.string().url().optional(),
    NEXT_PUBLIC_ENABLE_AI: z.enum(['true', 'false']).optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    OPENAI_VISION_MODEL: process.env.OPENAI_VISION_MODEL,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    STRIPE_PRO_PRICE_PLN: process.env.STRIPE_PRO_PRICE_PLN,
    STRIPE_PRO_PRICE_EUR: process.env.STRIPE_PRO_PRICE_EUR,
    STRIPE_PRO_PRICE_GBP: process.env.STRIPE_PRO_PRICE_GBP,
    STRIPE_PRO_PRICE_USD: process.env.STRIPE_PRO_PRICE_USD,
    STRIPE_PREMIUM_PRICE_PLN: process.env.STRIPE_PREMIUM_PRICE_PLN,
    STRIPE_PREMIUM_PRICE_EUR: process.env.STRIPE_PREMIUM_PRICE_EUR,
    STRIPE_PREMIUM_PRICE_GBP: process.env.STRIPE_PREMIUM_PRICE_GBP,
    STRIPE_PREMIUM_PRICE_USD: process.env.STRIPE_PREMIUM_PRICE_USD,
    BREVO_API_KEY: process.env.BREVO_API_KEY,
    BREVO_FROM_EMAIL: process.env.BREVO_FROM_EMAIL,
    CONTACT_INBOX_EMAIL: process.env.CONTACT_INBOX_EMAIL,
    SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    CRON_SECRET: process.env.CRON_SECRET,
    POSTHOG_API_KEY: process.env.POSTHOG_API_KEY,
    ENABLE_AI: process.env.ENABLE_AI,
    SUPABASE_URL: process.env.SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
    NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_ENABLE_AI: process.env.NEXT_PUBLIC_ENABLE_AI,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
